version: '2.1'

services:

  flyway:
    image: boxfuse/flyway:5-alpine
    command: -url=jdbc:postgresql://postgrestest:5432/postgres -schemas=public -user=postgres -password=qwerty
    volumes:
      - postgres-volume:${PWD}/src/main/resources/db/migration/
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:14.5-alpine'
    hostname: postgrestest
    restart: always
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: public
    networks:
      - testnetwork
    healthcheck:
      test: echo "hello"

  app:
    build: .
    container_name: 'calendar-app'
    depends_on:
      postgres:
        condition: service_healthy
      flyway:
          condition: service_completed_successfully
    hostname: calendarapp
    ports:
     - 8080:8080
    environment:
      POSTGRES_HOST: postgres
      restart: always
    networks:
      - testnetwork

  ubuntu:
    image: ubuntu
    restart: always
    hostname: aboba-bubuntu
    tty: true
    container_name: ubuntu

  bubuntu:
    image: ubuntu
    restart: always
    hostname: abobaboba
    tty: true
    container_name: bubuntu

volumes:
  postgres-volume:

networks:
  testnetwork:
    name: testnetwork
    internal: true
