version: '2.1'

services:

  app:
    build: ./
    container_name: 'calendar-app'
    depends_on:
      - postgres
    hostname: calendar-app
    ports:
      - 8080:8080
    environment:
      POSTGRES_HOST: postgres
    restart: always

#  flyway:
#    image: boxfuse/flyway:5-alpine
#    command: -url=jdbc:postgresql://postgres:5432/postgres -schemas=public -user=postgres -password=qwerty
#    volumes:
#      - ./db/migration/sql
#    depends_on:
#      postgres:
#        condition: service_healthy

  postgres:
    image: 'postgres:14.5-alpine'
    hostname: java-postgres
    restart: always
    container_name: 'java-postgres'
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_SCHEMA: public

  ubuntu:
    image: ubuntu
    restart: always
    container_name: ubuntu
