CREATE TABLE credentials
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email    VARCHAR(255)                             NOT NULL,
    password VARCHAR(255)                             NOT NULL,
    user_id  INTEGER,
    CONSTRAINT pk_credentials PRIMARY KEY (id)
);

CREATE TABLE events
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title        VARCHAR(255)                             NOT NULL,
    workspace_id INTEGER,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

CREATE TABLE notes
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description VARCHAR(100)                             NOT NULL,
    event_id    INTEGER,
    CONSTRAINT pk_notes PRIMARY KEY (id)
);

CREATE TABLE users
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE workspaces
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(255),
    user_id INTEGER,
    CONSTRAINT pk_workspaces PRIMARY KEY (id)
);

ALTER TABLE credentials
    ADD CONSTRAINT uc_credentials_email UNIQUE (email);

ALTER TABLE credentials
    ADD CONSTRAINT FK_CREDENTIALS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_WORKSPACE FOREIGN KEY (workspace_id) REFERENCES workspaces (id);

ALTER TABLE notes
    ADD CONSTRAINT FK_NOTES_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE workspaces
    ADD CONSTRAINT FK_WORKSPACES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);